http:
  port: "8000"
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

cache:
  ttl: 60s

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"
